### ISSUE TITLE
Crashing on OpenViX

### ISSUE THREAD

**Issue by AbuBaniaz** [KravenHD/KravenFHD#2]
A user has reported a crash using OpenViX 5.0 027

```
<   668.931> [InfoBarGenerics] KEY: 399 GREEN
<   668.931> [ActionMap] ColorActions green
<   668.931> KravenPlugin: Save profile /etc/enigma2/kravenfhd_profile_1
<   669.059> Traceback (most recent call last):
<   669.059>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
<   669.059>   File "/usr/lib/enigma2/python/Plugins/Extensions/KravenFHD/KravenFHD.py", line 3748, in save
<   669.085>     if config.usage.movielist_show_picon.value == True:
<   669.085>   File "/usr/lib/enigma2/python/Components/config.py", line 1890, in __getattr__
<   669.087> KeyError: 'movielist_show_picon'
<   669.087> [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x64a4ce90>>,('ColorActions', 'green')) failed)
```

```
http://www.world-of-satellite.com/showthread.php?57833-KravenFHD-fails-on-latest-openVix-version&highlight=kravenfhd
```

[Enigma2_crash_2017-09-13_19-02-23.log.txt](https://github.com/KravenHD/KravenFHD/files/1311811/Enigma2_crash_2017-09-13_19-02-23.log.txt)

**Comment by ghost** [comment]
see WA in ATV git https://github.com/openatv/enigma2/blob/master/lib/python/Components/UsageConfig.py#L80

**Comment by dimuss** [comment]
Hi, are there any plans to fix this? I love this skin and can't use it for more than 2 months now.
